mvn install:install-file -Dfile=./apptemplate.jar -DgroupId=com.genesys -DartifactId=apptemplate -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./comappblock.jar -DgroupId=com.genesys -DartifactId=comappblock -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./commons.jar -DgroupId=com.genesys -DartifactId=commons -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./commonsappblock.jar -DgroupId=com.genesys -DartifactId=commonsappblock -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./configurationprotocol.jar -DgroupId=com.genesys -DartifactId=configurationprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./connection.jar -DgroupId=com.genesys -DartifactId=connection -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./contactsprotocol.jar -DgroupId=com.genesys -DartifactId=contactsprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./kvlistbinding.jar -DgroupId=com.genesys -DartifactId=kvlistbinding -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./kvlists.jar -DgroupId=com.genesys -DartifactId=kvlists -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./logging.jar -DgroupId=com.genesys -DartifactId=logging -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./managementprotocol.jar -DgroupId=com.genesys -DartifactId=managementprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./messagebrokerappblock.jar -DgroupId=com.genesys -DartifactId=messagebrokerappblock -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./netty-3.9.4.Final.jar -DgroupId=com.genesys -DartifactId=netty -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./openmediaprotocol.jar -DgroupId=com.genesys -DartifactId=openmediaprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./outboundprotocol.jar -DgroupId=com.genesys -DartifactId=outboundprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./protocol.jar -DgroupId=com.genesys -DartifactId=protocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./protocolmanagerappblock.jar -DgroupId=com.genesys -DartifactId=protocolmanagerappblock -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./reportingprotocol.jar -DgroupId=com.genesys -DartifactId=reportingprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./routingprotocol.jar -DgroupId=com.genesys -DartifactId=routingprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./system.jar -DgroupId=com.genesys -DartifactId=system -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./voiceprotocol.jar -DgroupId=com.genesys -DartifactId=voiceprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./warmstandbyappblock.jar -DgroupId=com.genesys -DartifactId=warmstandbyappblock -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./webmediaprotocol.jar -DgroupId=com.genesys -DartifactId=webmediaprotocol -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=./json_simple-1.0.2.jar -DgroupId=com.google -DartifactId=simple-json -Dversion=1.0 -Dpackaging=jar
